### ISSUE TITLE
Install DGL with Conda cuda 10 missing libcudart.so.9.2

### ISSUE THREAD

**Issue by vexilligera** [dmlc/dgl#919]
I installed DGL with Anaconda (Python 3.7) on EC2 p3.8xlarge with AMI 19.2 using the command:
conda install -c dglteam dgl-cuda10.0

Then in the python shell:
import dgl

Error message:
libcudart.so.9.2: cannot open shared object file: No such file or directory

Why does dgl-cuda10.0 uselibcudart.so.9.2? How should I fix the problem?

**Comment by vexilligera** [comment]
Fixed with pip installation. Still feels weird.

**Comment by jzhou316** [comment]
Came across the same issue. Yeah only pip works. Weird +1

**Comment by saikrishna-1996** [comment]
Yeah, same issue. and solved with pip. +1

**Comment by BarclayII** [comment]
Should be fixed for conda CUDA 9.0 and CUDA 10.0 packages now.

**Comment by tingkai-zhang** [comment]
> Should be fixed for conda CUDA 9.0 and CUDA 10.0 packages now.

Still have this error for CUDA 10.0 package
```
>>> import dgl.function as fn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.7/site-packages/dgl/__init__.py", line 6, in <module>
    from . import function
  File "/root/anaconda3/lib/python3.7/site-packages/dgl/function/__init__.py", line 5, in <module>
    from .message import *
  File "/root/anaconda3/lib/python3.7/site-packages/dgl/function/message.py", line 8, in <module>
    from ..runtime import ir
  File "/root/anaconda3/lib/python3.7/site-packages/dgl/runtime/__init__.py", line 4, in <module>
    from . import scheduler
  File "/root/anaconda3/lib/python3.7/site-packages/dgl/runtime/scheduler.py", line 4, in <module>
    from .. import utils
  File "/root/anaconda3/lib/python3.7/site-packages/dgl/utils.py", line 8, in <module>
    from .base import DGLError
  File "/root/anaconda3/lib/python3.7/site-packages/dgl/base.py", line 6, in <module>
    from ._ffi.base import DGLError  # pylint: disable=unused-import
  File "/root/anaconda3/lib/python3.7/site-packages/dgl/_ffi/base.py", line 42, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/root/anaconda3/lib/python3.7/site-packages/dgl/_ffi/base.py", line 34, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/root/anaconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory
```

**Comment by tingkai-zhang** [comment]
Unfortunately I didnt solve it with pip and still got the same error

**Comment by Zhiyu-Chen** [comment]
> Unfortunately I didnt solve it with pip and still got the same error

I met the same problem when I didn't install cuda toolkit. You may check whether your 'nvcc --version' works.
